[env:esp32dev]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    dawidchyrzynski/home-assistant-integration @ ^2.1.0
    mathieucarbou/AsyncTCP @ ^3.2.0
    mathieucarbou/ESPAsyncWebServer @ ^3.3.0
